# Supabase Edge Function Configuration

# Disable JWT verification for Vipps payment functions
[functions.vipps-create-order]
verify_jwt = false

[functions.vipps-check-status]
verify_jwt = false

[functions.vipps-callback]
verify_jwt = false

[functions.vipps-webhook]
verify_jwt = false

[functions.vipps-register-webhook]
verify_jwt = false

[functions.setup-webhooks]
verify_jwt = false 